server:
  port: 8088

logging:
  level:
    org.springframework: info

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver



  h2:
    console:
      enabled: true